# Generated by Django 4.2.4 on 2023-12-15 01:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=100)),
                ('real_name', models.CharField(max_length=100)),
                ('bands', models.CharField(max_length=200)),
                ('birth_year', models.IntegerField(max_length=4)),
                ('birth_month', models.CharField(choices=[('January', 'Jan'), ('February', 'Feb'), ('March', 'Mar'), ('April', 'Apr'), ('May', 'May'), ('June', 'Jun'), ('July', 'Jul'), ('August', 'Aug'), ('September', 'Sep'), ('October', 'Oct'), ('November', 'Nov'), ('December', 'Dec')], default='January', max_length=12)),
                ('birth_day', models.IntegerField(max_length=2)),
                ('birth_date', models.DateTimeField(unique_for_date=models.IntegerField(max_length=2), unique_for_month=models.CharField(choices=[('January', 'Jan'), ('February', 'Feb'), ('March', 'Mar'), ('April', 'Apr'), ('May', 'May'), ('June', 'Jun'), ('July', 'Jul'), ('August', 'Aug'), ('September', 'Sep'), ('October', 'Oct'), ('November', 'Nov'), ('December', 'Dec')], default='January', max_length=12), unique_for_year=models.IntegerField(max_length=4))),
                ('death_year', models.IntegerField(blank=True, max_length=4)),
                ('death_month', models.CharField(blank=True, choices=[('January', 'Jan'), ('February', 'Feb'), ('March', 'Mar'), ('April', 'Apr'), ('May', 'May'), ('June', 'Jun'), ('July', 'Jul'), ('August', 'Aug'), ('September', 'Sep'), ('October', 'Oct'), ('November', 'Nov'), ('December', 'Dec')], default='January', max_length=12)),
                ('death_day', models.IntegerField(blank=True, max_length=2)),
                ('death_date', models.DateTimeField(blank=True, unique_for_date=models.IntegerField(blank=True, max_length=2), unique_for_month=models.CharField(blank=True, choices=[('January', 'Jan'), ('February', 'Feb'), ('March', 'Mar'), ('April', 'Apr'), ('May', 'May'), ('June', 'Jun'), ('July', 'Jul'), ('August', 'Aug'), ('September', 'Sep'), ('October', 'Oct'), ('November', 'Nov'), ('December', 'Dec')], default='January', max_length=12), unique_for_year=models.IntegerField(blank=True, max_length=4))),
                ('about_section', models.TextField(max_length=10000)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
