# Generated by Django 4.2.4 on 2023-12-15 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='death_date',
        ),
    ]
