# Generated by Django 4.2.4 on 2023-12-15 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_remove_artist_birth_date_remove_artist_death_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='death_day',
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='death_month',
            field=models.CharField(blank=True, choices=[('January', 'Jan'), ('February', 'Feb'), ('March', 'Mar'), ('April', 'Apr'), ('May', 'May'), ('June', 'Jun'), ('July', 'Jul'), ('August', 'Aug'), ('September', 'Sep'), ('October', 'Oct'), ('November', 'Nov'), ('December', 'Dec')], default=None, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='death_year',
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
    ]
